version: "3.8"

services:
    app:
        container_name: pokemons
        build:
            context: .
            dockerfile: containers/php/Dockerfile
        volumes:
            - ./src:/var/www
        ports:
            - "${APP_HOST_PORT}"
        working_dir: /var/www

    nginx:
        image: nginx:alpine
        container_name: nginx-pokemons
        ports:
            - "${NGINX_HOST_PORT}"
        volumes:
            - ./src:/var/www
            - ./containers/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db

    db:
        image: postgres
        container_name: postgres-pokemons
        volumes:
            - ./containers/postgresql/data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_HOST_PORT}"
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

    db-test:
        image: postgres
        container_name: postgres-pokemons-test
        volumes:
            - ./containers/postgresql/test:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_TEST_HOST_PORT}"
        environment:
            POSTGRES_DB: "${POSTGRES_TEST_DB}"
            POSTGRES_USER: "${POSTGRES_TEST_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_TEST_PASSWORD}"
        command:
            - "postgres"
            - "-c"
            - "port=5433"

    elasticsearch:
        image: elasticsearch:7.17.17
        container_name: elasticsearch-pokemons
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./containers/elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - "${ELASTICSEARCH_HOST_PORT}"
